spring:
  application:
    name: cas-server
server:
  port: 9099
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false

security:
  cas:
    server:
      host: http://127.0.0.1:8080/cas
      login: ${security.cas.server.host}/login
      logout: ${security.cas.server.host}/logout
    service:
      host: http://localhost:9099
      login: /login/cas
      logout: /logout